import { FastifyPluginAsync } from "fastify";

const api: FastifyPluginAsync = async (fastify, opts): Promise<void> => {
  // Example hardcoded JSON

  fastify.get("/data", async (request, reply) => {
    return myData;
  });
};

const myData = {
  documents: [
    {
      id: "doc_1",
      title: "Tech Conference Highlights",
      text: "The 2025 Global Tech Summit in San Francisco featured talks by Alice Johnson from Acme Corp and Bob Smith from Delta Inc.",
    },
    {
      id: "doc_2",
      title: "Startup Funding News",
      text: "Acme Corporation announced a new funding round led by venture capitalist Robert Lee. Charlie Kim attended the announcement.",
    },
    {
      id: "doc_3",
      title: "International Politics Overview",
      text: "On March 15, 2025, representatives from Gamma LLC met with officials in Berlin. Eve Adams commented on the new policy changes.",
    },
    {
      id: "doc_4",
      title: "Cultural Festival Report",
      text: "The Berlin Spring Festival hosted performances by Sophia Müller and Oliver O'Neil. Zeta LLC sponsored the event.",
    },
  ],
  entities: [
    {
      id: "ent_1",
      name: "Alice Johnson",
      type: "PERSON",
      document_id: "doc_1",
      group_id: "group_1",
    },
    {
      id: "ent_2",
      name: "Alice J.",
      type: "PERSON",
      document_id: "doc_2",
      group_id: "group_1",
    },
    {
      id: "ent_3",
      name: "Bob Smith",
      type: "PERSON",
      document_id: "doc_1",
      group_id: "group_2",
    },
    {
      id: "ent_4",
      name: "Robert Lee",
      type: "PERSON",
      document_id: "doc_2",
      group_id: "group_2",
    },
    {
      id: "ent_5",
      name: "Charlie Kim",
      type: "PERSON",
      document_id: "doc_2",
      group_id: "group_3",
    },
    {
      id: "ent_6",
      name: "Eve Adams",
      type: "PERSON",
      document_id: "doc_3",
      group_id: "group_4",
    },
    {
      id: "ent_7",
      name: "Sophia Müller",
      type: "PERSON",
      document_id: "doc_4",
      group_id: "group_5",
    },
    {
      id: "ent_8",
      name: "Oliver O'Neil",
      type: "PERSON",
      document_id: "doc_4",
      group_id: "group_6",
    },
    {
      id: "ent_9",
      name: "Acme Corp",
      type: "ORG",
      document_id: "doc_1",
      group_id: "group_7",
    },
    {
      id: "ent_10",
      name: "Acme Corporation",
      type: "ORG",
      document_id: "doc_2",
      group_id: "group_7",
    },
    {
      id: "ent_11",
      name: "Delta Inc",
      type: "ORG",
      document_id: "doc_1",
      group_id: "group_8",
    },
    {
      id: "ent_12",
      name: "Gamma LLC",
      type: "ORG",
      document_id: "doc_3",
      group_id: "group_9",
    },
    {
      id: "ent_13",
      name: "Zeta LLC",
      type: "ORG",
      document_id: "doc_4",
      group_id: "group_10",
    },
    {
      id: "ent_14",
      name: "San Francisco",
      type: "LOC",
      document_id: "doc_1",
      group_id: "group_11",
    },
    {
      id: "ent_15",
      name: "Berlin",
      type: "LOC",
      document_id: "doc_3",
      group_id: "group_12",
    },
    {
      id: "ent_16",
      name: "Berlin",
      type: "LOC",
      document_id: "doc_4",
      group_id: "group_12",
    },
    {
      id: "ent_17",
      name: "2025 Global Tech Summit",
      type: "EVENT",
      document_id: "doc_1",
      group_id: "group_13",
    },
    {
      id: "ent_18",
      name: "Berlin Spring Festival",
      type: "EVENT",
      document_id: "doc_4",
      group_id: "group_14",
    },
    {
      id: "ent_19",
      name: "March 15, 2025",
      type: "DATE",
      document_id: "doc_3",
      group_id: "group_15",
    },
    {
      id: "ent_20",
      name: "2025",
      type: "DATE",
      document_id: "doc_1",
      group_id: "group_15",
    },
    {
      id: "ent_21",
      name: "New funding round",
      type: "EVENT",
      document_id: "doc_2",
      group_id: "group_16",
    },
    {
      id: "ent_22",
      name: "policy changes",
      type: "EVENT",
      document_id: "doc_3",
      group_id: "group_17",
    },
    {
      id: "ent_23",
      name: "venture capitalist",
      type: "ORG",
      document_id: "doc_2",
      group_id: "group_18",
    },
    {
      id: "ent_24",
      name: "representatives",
      type: "ORG",
      document_id: "doc_3",
      group_id: "group_19",
    },
    {
      id: "ent_25",
      name: "officials",
      type: "ORG",
      document_id: "doc_3",
      group_id: "group_20",
    },
    {
      id: "ent_26",
      name: "performances",
      type: "EVENT",
      document_id: "doc_4",
      group_id: "group_21",
    },
    {
      id: "ent_27",
      name: "announcement",
      type: "EVENT",
      document_id: "doc_2",
      group_id: "group_22",
    },
    {
      id: "ent_28",
      name: "Alice",
      type: "PERSON",
      document_id: "doc_3",
      group_id: "group_1",
    },
    {
      id: "ent_29",
      name: "Bob",
      type: "PERSON",
      document_id: "doc_3",
      group_id: "group_2",
    },
    {
      id: "ent_30",
      name: "Charlie",
      type: "PERSON",
      document_id: "doc_3",
      group_id: "group_3",
    },
    {
      id: "ent_31",
      name: "Eve",
      type: "PERSON",
      document_id: "doc_4",
      group_id: "group_4",
    },
    {
      id: "ent_32",
      name: "Acme",
      type: "ORG",
      document_id: "doc_3",
      group_id: "group_7",
    },
    {
      id: "ent_33",
      name: "Delta",
      type: "ORG",
      document_id: "doc_3",
      group_id: "group_8",
    },
    {
      id: "ent_34",
      name: "Gamma",
      type: "ORG",
      document_id: "doc_4",
      group_id: "group_9",
    },
    {
      id: "ent_35",
      name: "Zeta",
      type: "ORG",
      document_id: "doc_3",
      group_id: "group_10",
    },
    {
      id: "ent_36",
      name: "San Fran",
      type: "LOC",
      document_id: "doc_2",
      group_id: "group_11",
    },
    {
      id: "ent_37",
      name: "Oliver",
      type: "PERSON",
      document_id: "doc_3",
      group_id: "group_6",
    },
    {
      id: "ent_38",
      name: "Sophia",
      type: "PERSON",
      document_id: "doc_3",
      group_id: "group_5",
    },
    {
      id: "ent_39",
      name: "Festival",
      type: "EVENT",
      document_id: "doc_3",
      group_id: "group_14",
    },
    {
      id: "ent_40",
      name: "Tech Summit",
      type: "EVENT",
      document_id: "doc_2",
      group_id: "group_13",
    },
    {
      id: "ent_41",
      name: "March 2025",
      type: "DATE",
      document_id: "doc_2",
      group_id: "group_15",
    },
    {
      id: "ent_42",
      name: "Conference",
      type: "EVENT",
      document_id: "doc_1",
      group_id: "group_13",
    },
    {
      id: "ent_43",
      name: "Investment",
      type: "EVENT",
      document_id: "doc_2",
      group_id: "group_16",
    },
    {
      id: "ent_44",
      name: "Policy Update",
      type: "EVENT",
      document_id: "doc_3",
      group_id: "group_17",
    },
    {
      id: "ent_45",
      name: "Berlin Officials",
      type: "ORG",
      document_id: "doc_4",
      group_id: "group_20",
    },
    {
      id: "ent_46",
      name: "Sponsors",
      type: "ORG",
      document_id: "doc_4",
      group_id: "group_10",
    },
    {
      id: "ent_47",
      name: "Tech Talk",
      type: "EVENT",
      document_id: "doc_1",
      group_id: "group_13",
    },
    {
      id: "ent_48",
      name: "Berlin Meeting",
      type: "EVENT",
      document_id: "doc_3",
      group_id: "group_17",
    },
    {
      id: "ent_49",
      name: "Berlin Policy Event",
      type: "EVENT",
      document_id: "doc_3",
      group_id: "group_17",
    },
    {
      id: "ent_50",
      name: "Acme Funding",
      type: "EVENT",
      document_id: "doc_2",
      group_id: "group_16",
    },
  ],
  entity_groups: [
    { id: "group_1", name: "Alice Johnson" },
    { id: "group_2", name: "Bob Smith" },
    { id: "group_3", name: "Charlie Kim" },
    { id: "group_4", name: "Eve Adams" },
    { id: "group_5", name: "Sophia Müller" },
    { id: "group_6", name: "Oliver O'Neil" },
    { id: "group_7", name: "Acme Corp" },
    { id: "group_8", name: "Delta Inc" },
    { id: "group_9", name: "Gamma LLC" },
    { id: "group_10", name: "Zeta LLC" },
    { id: "group_11", name: "San Francisco" },
    { id: "group_12", name: "Berlin" },
    { id: "group_13", name: "Tech Summit" },
    { id: "group_14", name: "Berlin Spring Festival" },
    { id: "group_15", name: "2025" },
    { id: "group_16", name: "Funding Event" },
    { id: "group_17", name: "Policy Change" },
    { id: "group_18", name: "Venture Capitalist" },
    { id: "group_19", name: "Representatives" },
    { id: "group_20", name: "Officials" },
    { id: "group_21", name: "Performances" },
    { id: "group_22", name: "Announcement" },
  ],
};

export default api;
